# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps: 
- script: |
      bash envi_setup.sh apt 
     
     
    
  displayName: 'setup enviremnint script'

- script: |
     gunicorn --bind=0.0.0.0:4321 --workers=4 hello:app

  displayName: 'Run a hello App script'

# Start the deployment process
- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'Vm-samar@13.92.242.238'
    sourceFolder: 'hello_app/'
    contents: '**'
    targetFolder: '/var/www/html'
    cleanTargetFolder: true
    readyTimeout: '20000'
    failOnEmptySource: true 



