# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'ubuntu-latest'

steps: 

- script: |
    bash   setup.sh 
  displayName: 'setup enviremnint 1 script'

- script: |
   git clone https://github.com/samarziad/htu-ict-devops-cicd-webapp.git
  displayName: 'clone  github '

- script: |
    bash   setup2.sh
  displayName: 'setup enviremnint 2 script'

- task: CmdLine@2
  inputs:
    script: 'gunicorn --bind=0.0.0.0  --workers=4 hello:app'

- script: |
    bash    serverRun.sh
  displayName: ' serverRun.sh script'
