# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps: 
- script: |
     sudo apt update
     sudo apt-y upgrade
     sudo apt install -y python3-pip
     sudo apt install build-essential libssl-dev libffi-dev python3-dev
     sudo apt install -y python3-venv
     python3.6 -m venv my_env
     source my_env/bin/activate
     pip install requirements.txt
    
  displayName: 'setup enviremnint script'

- script: |
     sudo gunicorn --bind=0.0.0.0:4321 --workers=4 hello:app

  displayName: 'Run a hello.py script'

# Start the deployment process
- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'Vm-samar@13.92.242.238'
    sourceFolder: 'hello_app/'
    contents: '**'
    targetFolder: '/var/www/html'
    cleanTargetFolder: true
    readyTimeout: '20000'
    failOnEmptySource: true 



