# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'ubuntu-latest'

steps: 

- script: |
    bash   setup.sh 
  displayName: 'setup enviremnint 1 script'

- script: |
    trigger:
    - master
  displayName: 'clne  github '

- script: |
    bash   serverRun.sh 
  displayName: 'run server  script'

