# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'ubuntu-latest'
steps:


- script: |
     cd /var/www/html
     mkdir myWebproject
     cd myWebproject
  displayName: 'Make directr0ry '
    

- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'Vm-samar@13.92.242.238'
    sourceFolder: 'hello_app/'
    contents: '**'
    targetFolder: '/var/www/html'
    cleanTargetFolder: true
    readyTimeout: '20000'
    failOnEmptySource: true



- script: |
    bash setup.sh
  displayName: 'Run setup enviremint  script'
    

- script: |
    bash setup2.sh
  displayName: 'Run setup enviremint2  script'

- script: |
    bash serverRun.sh
  displayName: 'Run server script'
    